# Base configs
baseurl: ""
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-DJYCM9GH8Y"

# UI configs
title: "Théodore Pénicaut"
subtitle: ""
author: "Théodore Pénicaut"
header:
 title: "My Photos"
 subtitle: "by Théodore Pénicaut"
footer:
 name: "Hey there, my name is Théodore"
 bio: " I'm a beginner photograph, I mainly take pictures with my drone, a DJI mini 2SE. You will find here the best photos I've take with it.
   You can also check out my youtube page to see the videos I've taken with my FPV drone !!<br><br>

  All images displayed on this website are licensed under the.<a href='https://creativecommons.org/licenses/by-nc/4.0/' target='_blank' rel='noopener'>
    Creative Commons Attribution–NonCommercial 4.0 International (CC BY-NC 4.0)
  </a>. If you need an image for commercial use, please contact me via the contact form or through my social media."







social_urls:
  twitter: "https://x.com/HackTimail"
  instagram: "https://www.instagram.com/theodore.pnct"
  youtube: "https://www.youtube.com/@Hack_Timail" 
  github: "https://www.github.com/Hack_Timel"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
